flowchart TD;
	id0["obsession"] --> id1["debhelper(>=9)"];
	id0["obsession"] --> id2["libglib2.0-dev"];
	id0["obsession"] --> id3["libdbus-1-dev"];
	id0["obsession"] --> id4["libx11-dev"];
	id0["obsession"] --> id5["libgtk2.0-dev"];
	id0["obsession"] --> id6["valac"];
